[project]
name = "txt-style-transfer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=6.29.5",
    "litellm>=1.74.2",
    "pandas>=2.3.1",
    "tdqm>=0.0.1",
    "loguru>=0.7.3",
    "torch>=2.7.0",
    "torch-geometric>=2.6.1",
    "torchvision>=0.22.0",
    "transformers>=4.55.4",
    "mlflow>=3.4.0",
    "datasets>=3.4.1",
    "unsloth[windows]",
    "bert-score>=0.3.13",
    "bleu>=0.3",
    "evaluate>=0.4.6",
    "strands[litellm]>=0.1.0",
    "strands_agents_tools",
    "pip>=25.3",
    "strands-agents[litellm]>=1.14.0",
]
[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }
unsloth = { git = "https://github.com/unslothai/unsloth.git" }
strands-tools = { git = "https://github.com/strands-agents/tools.git" }
